### PR TITLE
feat: upgrade to Tailwind CSS v4

### PR DESCRIPTION
**Pull request by corrupt952**
## Summary
- Upgrade Tailwind CSS from v3.4.17 to v4.1.10
- Add @tailwindcss/postcss plugin for improved integration
- Remove autoprefixer dependency (now built into Tailwind v4)
- Update PostCSS configuration for v4 compatibility
- Update UI components and styles to use v4 syntax
- Remove legacy tailwind.config.js file

## Test plan
- [ ] Verify all UI components render correctly
- [ ] Test Storybook components display properly
- [ ] Confirm extension popup and content scripts work
- [ ] Check that all styles are applied correctly
- [ ] Run build process to ensure no compilation errors

🤖 Generated with [Claude Code](https://claude.ai/code)

### CODE REVIEW

**Comment by corrupt952** [comment]
Problem: Shadow DOM background color is transparent after upgrading to v4
